"""add_is_default_to_agents

Revision ID: 2134c480e33b
Revises: 1f322ba7c3a6
Create Date: 2026-06-24 22:56:02.137478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2134c480e33b'
down_revision: Union[str, Sequence[str], None] = '1f322ba7c3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_default')
    # ### end Alembic commands ###
