"""simplify_workspace_fields

Revision ID: b8f3fc6da372
Revises: 1b34324eb3c9
Create Date: 2026-06-07 10:48:54.919602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8f3fc6da372'
down_revision: Union[str, Sequence[str], None] = '1b34324eb3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'platform')
    op.drop_column('workspaces', 'platform_store_id')
    op.drop_column('workspaces', 'website')
    op.drop_column('workspaces', 'industry')
    op.drop_column('workspaces', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('platform_store_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('platform', postgresql.ENUM('manual', 'haravan', 'kiotviet', name='platformenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
